server:
  port: ${PORT:8080}

spring:
  application:
    name: market-web
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        hbm2ddl.auto: none
  messages:
    basename: messages
    fallback-to-system-locale: false
    use-code-as-default-message: true

---



spring:
  profiles: prod
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:1998/market
    driverClassName: org.postgresql.Driver
    username: postgres
    password: postgres
  thymeleaf:
    cache: true
    mode: HTML
    encoding: UTF-8